services:

  mockserver:
    image: mockserver/mockserver:5.15.0
    container_name: backend
    volumes:
      - ./mockserver:/config
    ports:
      - "9030:1080"

  zipkin:
    image: openzipkin/zipkin-slim:3.4.2
    container_name: sampler
    ports:
      - "9040:9411"
