###
GET http://localhost:9000/anonymous

###
GET http://localhost:9000/something
foo-name: foo-value

###
GET http://localhost:9000/somethingElse

###
GET localhost:9010/actuator/info

###
GET localhost:9010/actuator/health
